[2025-09-20T04:42:47.281+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-20T04:42:47.456+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_logistics_ticket_classifier_full_dag.send_email manual__2025-09-18T10:55:18.311962+00:00 [queued]>
[2025-09-20T04:42:47.525+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_logistics_ticket_classifier_full_dag.send_email manual__2025-09-18T10:55:18.311962+00:00 [queued]>
[2025-09-20T04:42:47.527+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-20T04:42:47.627+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): send_email> on 2025-09-18 10:55:18.311962+00:00
[2025-09-20T04:42:47.655+0000] {standard_task_runner.py:63} INFO - Started process 221 to run task
[2025-09-20T04:42:47.664+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', '4_logistics_ticket_classifier_full_dag', 'send_email', 'manual__2025-09-18T10:55:18.311962+00:00', '--job-id', '1097', '--raw', '--subdir', 'DAGS_FOLDER/4_logistics_ticket_classifier_full_dag.py', '--cfg-path', '/tmp/tmpi9hn89rh']
[2025-09-20T04:42:47.678+0000] {standard_task_runner.py:91} INFO - Job 1097: Subtask send_email
[2025-09-20T04:42:47.992+0000] {task_command.py:426} INFO - Running <TaskInstance: 4_logistics_ticket_classifier_full_dag.send_email manual__2025-09-18T10:55:18.311962+00:00 [running]> on host 9d1b71842418
[2025-09-20T04:42:48.281+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_logistics_ticket_classifier_full_dag' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T10:55:18.311962+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T10:55:18.311962+00:00'
[2025-09-20T04:42:48.284+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-20T04:42:48.485+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-09-20T04:42:49.005+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-20T04:42:49.007+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/4_logistics_ticket_classifier_full_dag.py", line 143, in send_email_with_data
    client.send_email(
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.MessageRejected: An error occurred (MessageRejected) when calling the SendEmail operation: Email address is not verified. The following identities failed the check in region AP-SOUTH-1: benjaminimp10@gmail.com, velms2024@gmail.com
[2025-09-20T04:42:49.108+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=4_logistics_ticket_classifier_full_dag, task_id=send_email, run_id=manual__2025-09-18T10:55:18.311962+00:00, execution_date=20250918T105518, start_date=20250920T044247, end_date=20250920T044249
[2025-09-20T04:42:49.120+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/utils/context.py:212 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-09-20T04:42:49.492+0000] {aws_utils.py:34} INFO - SNS alert sent for failed task: 4_logistics_ticket_classifier_full_dag.send_email
[2025-09-20T04:42:49.582+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1097 for task send_email (An error occurred (MessageRejected) when calling the SendEmail operation: Email address is not verified. The following identities failed the check in region AP-SOUTH-1: benjaminimp10@gmail.com, velms2024@gmail.com; 221)
[2025-09-20T04:42:49.646+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-20T04:42:49.699+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T04:42:49.703+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
