[2025-09-12T17:22:23.347+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T17:22:23.650+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_logistics_gold_metrics_dbt.dbt_run_gold manual__2025-09-12T17:18:10.203989+00:00 [queued]>
[2025-09-12T17:22:23.754+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_logistics_gold_metrics_dbt.dbt_run_gold manual__2025-09-12T17:18:10.203989+00:00 [queued]>
[2025-09-12T17:22:23.758+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-12T17:22:24.009+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_gold> on 2025-09-12 17:18:10.203989+00:00
[2025-09-12T17:22:24.041+0000] {standard_task_runner.py:63} INFO - Started process 2230 to run task
[2025-09-12T17:22:24.057+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', '3_logistics_gold_metrics_dbt', 'dbt_run_gold', 'manual__2025-09-12T17:18:10.203989+00:00', '--job-id', '1071', '--raw', '--subdir', 'DAGS_FOLDER/3_logistics-gold-metrics-dbt.py', '--cfg-path', '/tmp/tmp0_mht6ll']
[2025-09-12T17:22:24.075+0000] {standard_task_runner.py:91} INFO - Job 1071: Subtask dbt_run_gold
[2025-09-12T17:22:27.459+0000] {task_command.py:426} INFO - Running <TaskInstance: 3_logistics_gold_metrics_dbt.dbt_run_gold manual__2025-09-12T17:18:10.203989+00:00 [running]> on host c4b06dd52c37
[2025-09-12T17:22:28.777+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_eng' AIRFLOW_CTX_DAG_ID='3_logistics_gold_metrics_dbt' AIRFLOW_CTX_TASK_ID='dbt_run_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T17:18:10.203989+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T17:18:10.203989+00:00'
[2025-09-12T17:22:28.780+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T17:22:28.844+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-12T17:22:28.848+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/dbt/dbt-project && dbt run --select path:models/gold/']
[2025-09-12T17:22:28.907+0000] {subprocess.py:86} INFO - Output:
[2025-09-12T17:22:38.223+0000] {subprocess.py:93} INFO - [0m17:22:38  Running with dbt=1.8.8
[2025-09-12T17:22:41.811+0000] {subprocess.py:93} INFO - [0m17:22:41  Registered adapter: snowflake=1.8.4
[2025-09-12T17:22:53.587+0000] {subprocess.py:93} INFO - [0m17:22:53  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-12T17:22:53.592+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-12T17:22:53.593+0000] {subprocess.py:93} INFO - - snapshots.customers
[2025-09-12T17:22:55.001+0000] {subprocess.py:93} INFO - [0m17:22:55  Found 18 models, 1 snapshot, 1 seed, 24 data tests, 8 sources, 726 macros
[2025-09-12T17:22:55.041+0000] {subprocess.py:93} INFO - [0m17:22:55
[2025-09-12T17:23:00.446+0000] {subprocess.py:93} INFO - [0m17:23:00  Concurrency: 3 threads (target='dev')
[2025-09-12T17:23:00.464+0000] {subprocess.py:93} INFO - [0m17:23:00
[2025-09-12T17:23:00.507+0000] {subprocess.py:93} INFO - [0m17:23:00  1 of 8 START sql table model gold.customer_experience_summary .................. [RUN]
[2025-09-12T17:23:00.511+0000] {subprocess.py:93} INFO - [0m17:23:00  2 of 8 START sql view model gold.delivery_performance_by_courier ............... [RUN]
[2025-09-12T17:23:00.516+0000] {subprocess.py:93} INFO - [0m17:23:00  3 of 8 START sql view model gold.delivery_sla_rootcause ........................ [RUN]
[2025-09-12T17:23:04.266+0000] {subprocess.py:93} INFO - [0m17:23:04  3 of 8 OK created sql view model gold.delivery_sla_rootcause ................... [[32mSUCCESS 1[0m in 3.72s]
[2025-09-12T17:23:04.302+0000] {subprocess.py:93} INFO - [0m17:23:04  4 of 8 START sql table model gold.dm_inventory_status .......................... [RUN]
[2025-09-12T17:23:04.714+0000] {subprocess.py:93} INFO - [0m17:23:04  1 of 8 ERROR creating sql table model gold.customer_experience_summary ......... [[31mERROR[0m in 4.16s]
[2025-09-12T17:23:04.755+0000] {subprocess.py:93} INFO - [0m17:23:04  5 of 8 START sql table model gold.dm_order_fulfillment ......................... [RUN]
[2025-09-12T17:23:04.913+0000] {subprocess.py:93} INFO - [0m17:23:04  2 of 8 OK created sql view model gold.delivery_performance_by_courier .......... [[32mSUCCESS 1[0m in 4.36s]
[2025-09-12T17:23:05.050+0000] {subprocess.py:93} INFO - [0m17:23:05  6 of 8 START sql table model gold.order_to_delivery_lifecycle .................. [RUN]
[2025-09-12T17:23:08.967+0000] {subprocess.py:93} INFO - [0m17:23:08  4 of 8 OK created sql table model gold.dm_inventory_status ..................... [[32mSUCCESS 1[0m in 4.64s]
[2025-09-12T17:23:09.008+0000] {subprocess.py:93} INFO - [0m17:23:09  7 of 8 START sql table model gold.seller_performance ........................... [RUN]
[2025-09-12T17:23:09.027+0000] {subprocess.py:93} INFO - [0m17:23:09  5 of 8 OK created sql table model gold.dm_order_fulfillment .................... [[32mSUCCESS 1[0m in 4.23s]
[2025-09-12T17:23:09.093+0000] {subprocess.py:93} INFO - [0m17:23:09  8 of 8 START sql view model gold.seller_product_profitability .................. [RUN]
[2025-09-12T17:23:10.748+0000] {subprocess.py:93} INFO - [0m17:23:10  6 of 8 OK created sql table model gold.order_to_delivery_lifecycle ............. [[32mSUCCESS 1[0m in 4.94s]
[2025-09-12T17:23:11.938+0000] {subprocess.py:93} INFO - [0m17:23:11  7 of 8 OK created sql table model gold.seller_performance ...................... [[32mSUCCESS 1[0m in 2.89s]
[2025-09-12T17:23:11.977+0000] {subprocess.py:93} INFO - [0m17:23:11  8 of 8 OK created sql view model gold.seller_product_profitability ............. [[32mSUCCESS 1[0m in 2.84s]
[2025-09-12T17:23:12.042+0000] {subprocess.py:93} INFO - [0m17:23:12
[2025-09-12T17:23:12.046+0000] {subprocess.py:93} INFO - [0m17:23:12  Finished running 3 view models, 5 table models in 0 hours 0 minutes and 16.97 seconds (16.97s).
[2025-09-12T17:23:13.622+0000] {subprocess.py:93} INFO - [0m17:23:13
[2025-09-12T17:23:13.629+0000] {subprocess.py:93} INFO - [0m17:23:13  [31mCompleted with 1 error and 0 warnings:[0m
[2025-09-12T17:23:13.632+0000] {subprocess.py:93} INFO - [0m17:23:13
[2025-09-12T17:23:13.650+0000] {subprocess.py:93} INFO - [0m17:23:13    Database Error in model customer_experience_summary (models/gold/customer_experience_summary.sql)
[2025-09-12T17:23:13.660+0000] {subprocess.py:93} INFO -   002003 (42S02): SQL compilation error:
[2025-09-12T17:23:13.661+0000] {subprocess.py:93} INFO -   Object 'LOGISTICS_DEMO_1.GOLD.CONTROL_TABLE' does not exist or not authorized.
[2025-09-12T17:23:13.663+0000] {subprocess.py:93} INFO -   compiled code at target/run/logistics_project/models/gold/customer_experience_summary.sql
[2025-09-12T17:23:13.679+0000] {subprocess.py:93} INFO - [0m17:23:13
[2025-09-12T17:23:13.688+0000] {subprocess.py:93} INFO - [0m17:23:13  Done. PASS=7 WARN=0 ERROR=1 SKIP=0 TOTAL=8
[2025-09-12T17:23:18.097+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-12T17:23:18.100+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T17:23:18.167+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-12T17:23:18.199+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=3_logistics_gold_metrics_dbt, task_id=dbt_run_gold, run_id=manual__2025-09-12T17:18:10.203989+00:00, execution_date=20250912T171810, start_date=20250912T172223, end_date=20250912T172318
[2025-09-12T17:23:18.415+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1071 for task dbt_run_gold (Bash command failed. The command returned a non-zero exit code 1.; 2230)
[2025-09-12T17:23:18.483+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-12T17:23:18.556+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-12T17:23:18.562+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
