[2025-09-12T17:46:27.360+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T17:46:27.479+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_logistics_gold_metrics_dbt.dbt_run_gold manual__2025-09-12T17:43:36.182577+00:00 [queued]>
[2025-09-12T17:46:27.526+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_logistics_gold_metrics_dbt.dbt_run_gold manual__2025-09-12T17:43:36.182577+00:00 [queued]>
[2025-09-12T17:46:27.527+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-12T17:46:27.685+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_gold> on 2025-09-12 17:43:36.182577+00:00
[2025-09-12T17:46:27.701+0000] {standard_task_runner.py:63} INFO - Started process 2858 to run task
[2025-09-12T17:46:27.710+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', '3_logistics_gold_metrics_dbt', 'dbt_run_gold', 'manual__2025-09-12T17:43:36.182577+00:00', '--job-id', '1075', '--raw', '--subdir', 'DAGS_FOLDER/3_logistics-gold-metrics-dbt.py', '--cfg-path', '/tmp/tmpbedmii65']
[2025-09-12T17:46:27.716+0000] {standard_task_runner.py:91} INFO - Job 1075: Subtask dbt_run_gold
[2025-09-12T17:46:27.915+0000] {task_command.py:426} INFO - Running <TaskInstance: 3_logistics_gold_metrics_dbt.dbt_run_gold manual__2025-09-12T17:43:36.182577+00:00 [running]> on host c4b06dd52c37
[2025-09-12T17:46:28.224+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_eng' AIRFLOW_CTX_DAG_ID='3_logistics_gold_metrics_dbt' AIRFLOW_CTX_TASK_ID='dbt_run_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T17:43:36.182577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T17:43:36.182577+00:00'
[2025-09-12T17:46:28.226+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T17:46:28.272+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-12T17:46:28.275+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/dbt/dbt-project && dbt run --select path:models/gold/']
[2025-09-12T17:46:28.302+0000] {subprocess.py:86} INFO - Output:
[2025-09-12T17:46:35.119+0000] {subprocess.py:93} INFO - [0m17:46:35  Running with dbt=1.8.8
[2025-09-12T17:46:43.729+0000] {subprocess.py:93} INFO - [0m17:46:43  Registered adapter: snowflake=1.8.4
[2025-09-12T17:46:55.429+0000] {subprocess.py:93} INFO - [0m17:46:55  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-12T17:46:55.430+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-12T17:46:55.431+0000] {subprocess.py:93} INFO - - snapshots.customers
[2025-09-12T17:46:56.183+0000] {subprocess.py:93} INFO - [0m17:46:56  Found 18 models, 1 snapshot, 1 seed, 24 data tests, 8 sources, 726 macros
[2025-09-12T17:46:56.256+0000] {subprocess.py:93} INFO - [0m17:46:56
[2025-09-12T17:47:05.282+0000] {subprocess.py:93} INFO - [0m17:47:05  Concurrency: 3 threads (target='dev')
[2025-09-12T17:47:05.287+0000] {subprocess.py:93} INFO - [0m17:47:05
[2025-09-12T17:47:05.333+0000] {subprocess.py:93} INFO - [0m17:47:05  1 of 8 START sql table model gold.customer_experience_summary .................. [RUN]
[2025-09-12T17:47:05.336+0000] {subprocess.py:93} INFO - [0m17:47:05  2 of 8 START sql view model gold.delivery_performance_by_courier ............... [RUN]
[2025-09-12T17:47:05.340+0000] {subprocess.py:93} INFO - [0m17:47:05  3 of 8 START sql view model gold.delivery_sla_rootcause ........................ [RUN]
[2025-09-12T17:47:07.748+0000] {subprocess.py:93} INFO - [0m17:47:07  2 of 8 OK created sql view model gold.delivery_performance_by_courier .......... [[32mSUCCESS 1[0m in 2.37s]
[2025-09-12T17:47:07.755+0000] {subprocess.py:93} INFO - [0m17:47:07  3 of 8 OK created sql view model gold.delivery_sla_rootcause ................... [[32mSUCCESS 1[0m in 2.39s]
[2025-09-12T17:47:07.779+0000] {subprocess.py:93} INFO - [0m17:47:07  4 of 8 START sql table model gold.dm_inventory_status .......................... [RUN]
[2025-09-12T17:47:07.785+0000] {subprocess.py:93} INFO - [0m17:47:07  5 of 8 START sql table model gold.dm_order_fulfillment ......................... [RUN]
[2025-09-12T17:47:07.916+0000] {subprocess.py:93} INFO - [0m17:47:07  1 of 8 ERROR creating sql table model gold.customer_experience_summary ......... [[31mERROR[0m in 2.55s]
[2025-09-12T17:47:07.942+0000] {subprocess.py:93} INFO - [0m17:47:07  6 of 8 START sql table model gold.order_to_delivery_lifecycle .................. [RUN]
[2025-09-12T17:47:10.467+0000] {subprocess.py:93} INFO - [0m17:47:10  5 of 8 OK created sql table model gold.dm_order_fulfillment .................... [[32mSUCCESS 1[0m in 2.67s]
[2025-09-12T17:47:10.476+0000] {subprocess.py:93} INFO - [0m17:47:10  7 of 8 START sql table model gold.seller_performance ........................... [RUN]
[2025-09-12T17:47:10.838+0000] {subprocess.py:93} INFO - [0m17:47:10  6 of 8 OK created sql table model gold.order_to_delivery_lifecycle ............. [[32mSUCCESS 1[0m in 2.87s]
[2025-09-12T17:47:10.842+0000] {subprocess.py:93} INFO - [0m17:47:10  4 of 8 OK created sql table model gold.dm_inventory_status ..................... [[32mSUCCESS 1[0m in 3.05s]
[2025-09-12T17:47:10.857+0000] {subprocess.py:93} INFO - [0m17:47:10  8 of 8 START sql view model gold.seller_product_profitability .................. [RUN]
[2025-09-12T17:47:13.764+0000] {subprocess.py:93} INFO - [0m17:47:13  7 of 8 OK created sql table model gold.seller_performance ...................... [[32mSUCCESS 1[0m in 2.61s]
[2025-09-12T17:47:13.944+0000] {subprocess.py:93} INFO - [0m17:47:13  8 of 8 OK created sql view model gold.seller_product_profitability ............. [[32mSUCCESS 1[0m in 2.52s]
[2025-09-12T17:47:14.213+0000] {subprocess.py:93} INFO - [0m17:47:14
[2025-09-12T17:47:14.228+0000] {subprocess.py:93} INFO - [0m17:47:14  Finished running 3 view models, 5 table models in 0 hours 0 minutes and 17.92 seconds (17.92s).
[2025-09-12T17:47:16.226+0000] {subprocess.py:93} INFO - [0m17:47:16
[2025-09-12T17:47:16.258+0000] {subprocess.py:93} INFO - [0m17:47:16  [31mCompleted with 1 error and 0 warnings:[0m
[2025-09-12T17:47:16.281+0000] {subprocess.py:93} INFO - [0m17:47:16
[2025-09-12T17:47:16.299+0000] {subprocess.py:93} INFO - [0m17:47:16    Database Error in model customer_experience_summary (models/gold/customer_experience_summary.sql)
[2025-09-12T17:47:16.320+0000] {subprocess.py:93} INFO -   002003 (42S02): SQL compilation error:
[2025-09-12T17:47:16.350+0000] {subprocess.py:93} INFO -   Object 'LOGISTICS_DEMO_1.GOLD.CONTROL_TABLE' does not exist or not authorized.
[2025-09-12T17:47:16.378+0000] {subprocess.py:93} INFO -   compiled code at target/run/logistics_project/models/gold/customer_experience_summary.sql
[2025-09-12T17:47:16.401+0000] {subprocess.py:93} INFO - [0m17:47:16
[2025-09-12T17:47:16.420+0000] {subprocess.py:93} INFO - [0m17:47:16  Done. PASS=7 WARN=0 ERROR=1 SKIP=0 TOTAL=8
[2025-09-12T17:47:20.556+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-12T17:47:20.558+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T17:47:20.620+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-12T17:47:20.647+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=3_logistics_gold_metrics_dbt, task_id=dbt_run_gold, run_id=manual__2025-09-12T17:43:36.182577+00:00, execution_date=20250912T174336, start_date=20250912T174627, end_date=20250912T174720
[2025-09-12T17:47:21.264+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1075 for task dbt_run_gold (Bash command failed. The command returned a non-zero exit code 1.; 2858)
[2025-09-12T17:47:21.441+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-12T17:47:21.505+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-12T17:47:21.515+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
